export const ADD_POINT="POINT/ADD_POINT"
export const REMOVE_POINT="POINT/REMOVE_POINT"
export const GET_POINTS="POINT/GET_POINTS"
export const SET_KEYFRAMES="POINT/SET_KEYFRAMES"
export const ENABLE_AINMATION="AINMATION/ENABLE_AINMATION"
export const DISABLE_AINMATION="AINMATION/DISABLE_AINMATION"
export const SET_USER="USER/SET_USER"
export const RESET_USER="USER/RESET_USER"

